# Generated by Django 5.2.8 on 2023-03-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_partcipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='partcipants',
            new_name='participants',
        ),
    ]
